w3itch-crafter/w3itch-frontend

api/backend.ts
api/users.ts
pages/user/settings/index.tsx
types/index.ts
utils/index.ts

```bash
```
Better backend error handle.
**Desktop:**
- OS:
Chrome

perf: better backend error handle

---

components/pages/gameCarousel.tsx

```bash
```
Game carousel default position is index zero.
**Desktop:**
- OS:

fix: game carousel default position is index zero

---

components/layout/userPanel.tsx
pages/register.tsx
pages/user/settings/index.tsx
utils/error.ts
utils/index.ts
utils/user.ts

```bash
```
**Desktop:**
- OS:

refactor: use userHostUrl utils

---

utils/explorer.ts

```bash
```
**Desktop:**
- OS:

fix: revert remove URL but remove import URL from node.js

---

api/games.ts
components/pages/gameCell.tsx
pages/_app.tsx
pages/dashboard/index.tsx
pages/game/[id].tsx
styles/dashboard.module.scss
types/Api.d.ts

```bash
```
#45 
**Desktop:**
- OS:

feat: delete game on dashboard

---

api/users.ts
components/Game/EmbedWidget.tsx
components/forms/inputRow.tsx
pages/register.tsx
types/Api.d.ts

```bash
```
Fixes #57
**Desktop:**
- OS:

fix: validate username when register

---

components/layout/footer.tsx
components/pages/connectWallet.tsx
constants/chains.ts
pages/_app.tsx
pages/login.tsx

```bash
```
fix: better wallet connect error message #63
refactor: new login process and show backend login error message #62 
**Desktop:**
- OS:
Remove if no visual …

fix: better wallet connect error message and more

---

.env
constants/chains.ts
pages/register.tsx

```bash
```
Fixes #72
**Desktop:**
- OS:

fix: record user info when user signup

---

__tests__/utils/url.test.ts
pages/index.tsx
utils/index.ts
utils/url.ts
utils/user.ts

```bash
```
**Desktop:**
- OS:

refactor: move user profile wildcard test logic to utils

---

components/Game/Form.tsx
components/Game/FormCharset.tsx
components/UploadGameScreenshots/index.tsx
pages/game/[id].tsx
styles/game/id.module.scss

```bash
```
#75 
#70 
#71 
**Desktop:**
- OS:

feat: modify page styles, support delete screenshots

---

api/games.ts
components/Game/Download.tsx
pages/game/[id].tsx
utils/file.ts

```bash
```
#74 
**Desktop:**
- OS:

feat: download game file

---

components/Game/EmbedWidget.tsx
components/Game/Form.tsx
components/Game/FormPricing.tsx
components/Game/Screenshots.tsx
components/TokenList/TokenItem.tsx
components/TokenList/index.tsx
components/TokenLogo/index.tsx
constants/chains.ts
constants/contracts.ts
constants/index.ts
constants/providers.ts
constants/tokenList.ts
hooks/index.ts
hooks/useERC20Multicall.ts
hooks/useMulticall.ts
hooks/useTitle.ts
hooks/useTokens.ts
hooks/useTokensList.ts
next-seo.config.js
package.json
pages/_app.tsx
pages/game/[id].tsx
styles/common.module.scss
styles/game/id.module.scss
types/enum.ts
types/index.ts
yarn.lock

```bash
```
#87 
#79
#86 
**Desktop:**
- OS:

feat: support multi-chain token, SEO

---

components/icons/index.tsx
components/layout/userPanel.tsx
components/pages/gameCell.tsx

```bash
```
**Desktop:**
- OS:

fix: accessibility

---

pages/profile/_home.tsx

```bash
```
#111 
**Desktop:**
- OS:

fix: games list

---

constants/contracts.ts
constants/index.ts
constants/lists.ts
constants/providers.ts
constants/tokenList.ts
hooks/useTokens.ts

```bash
```
#110 
**Desktop:**
- OS:

feat: support token

---

next.config.js

```bash
```
**Desktop:**
- OS:

fix: add image domain

---

package.json

```bash
```
update package version to 0.2.0
**Desktop:**
- OS:

build: update package version to 0.2.0

---

.env

```bash
NEXT_PUBLIC_CHAIN_ID=1,3,4,5,42,56,97
```
**Desktop:**
- OS:

feat: update env

---

components/layout/navbar.tsx
components/layout/userPanel.tsx

```bash
```
**Desktop:**
- OS:

feat: update google search

---

components/layout/footer.tsx
pages/_offline.tsx

```bash
```
#120 
#122 
**Desktop:**
- OS:

feat: modify offline text, fix game detail tool display

---

components/Game/MoreInformation.tsx
components/pages/gameCell.tsx

```bash
```
#141
**Desktop:**
- OS:

fix: change Author to Submitter

---

.gitignore
next-sitemap.js
package.json
pages/game/edit/[id].tsx
yarn.lock

```bash
```
#129 
**Desktop:**
- OS:

feat: add default sitemap

---

package.json

```bash
```
#129 
**Desktop:**
- OS:

fix: fix postbuild

---

public/google194cdf6a4030f800.html

```bash
```
**Desktop:**
- OS:

feat: create test google-site-verification

---

pages/server-sitemap-index.xml/index.tsx

```bash
```
**Desktop:**
- OS:

feat: comment

---

pages/server-sitemap-index.xml/index.tsx

```bash
```
**Desktop:**
- OS:

fix: fix sitemap url

---

next-sitemap.js
pages/server-sitemap-index.xml/index.tsx
pages/server-sitemap.xml/index.tsx

```bash
```
**Desktop:**
- OS:

fix: fix sitemap fields

---

next-seo.config.js
pages/_app.tsx
pages/game/[id].tsx
utils/seo.ts

```bash
```
**Desktop:**
- OS:

feat: seo keywords jsonLd

---

api/account.ts
components/Game/Form.tsx
components/buttons.tsx
components/icons/index.tsx
components/pages/authentication.tsx
components/pages/loginMethodChooser.tsx
hooks/useAccount.ts
hooks/useERC20Multicall.ts
pages/login.tsx
pages/register.tsx
pages/user/settings/connected-accounts.tsx
types/index.ts
utils/chains.ts

```bash
```
Fixes #81
**Desktop:**
- OS:

feat: add oauth bind buttons

---

.env
components/layout/layout.tsx
components/layout/navbar.tsx
next-i18next.config.js
pages/_app.tsx
pages/_home.tsx
pages/games.tsx
pages/profile/_home.tsx
public/locales/en/common.json
public/locales/zh/common.json

```bash
```
**Desktop:**
- OS:

fix: i18n bugfix

---

components/layout/layout.tsx
components/layout/navbar.tsx
components/layout/userPanel.tsx
i18next-parser.config.js
next-i18next.config.js
package.json
pages/_app.tsx
pages/_home.tsx
pages/games.tsx
pages/profile/_home.tsx
pages/register.tsx
public/locales/en/common.json
public/locales/zh/common.json
yarn.lock

```bash
```
**Desktop:**
- OS:

feat: i18n auto language

---

next-i18next.config.js

serverSideTranslations crashes when called inside getServerSideProps on Vercel
```bash
```
**Desktop:**
- OS:

fix: fix i18n path

---

components/Game/Form.tsx
pages/dashboard/index.tsx

```bash
```
**Desktop:**
- OS:

refactor: change facebook link to discord link & hide quality guidelines

---

components/Game/Form.tsx
components/Game/FormAppStoreLinks.tsx
components/Game/FormCharset.tsx
components/Game/FormCommunity.tsx
components/Game/FormGenre.tsx
components/Game/FormPricing.tsx
components/Game/FormTags.tsx
components/UploadGameCover/index.tsx
components/UploadGameScreenshots/index.tsx
context/gameFormContext.tsx
pages/dashboard/index.tsx
pages/game/edit/[id].tsx
pages/game/new.tsx

```bash
```
#134 
**Desktop:**
- OS:

feat: game form use context

---

algolia.js
components/Search/index.tsx
constants/algolia.ts
constants/index.ts
package.json
pages/api/algolia/games/[id].ts
pages/api/algolia/games/index.ts
pages/api/algolia/games/initialization.ts
utils/algolia.ts

```bash
NEXT_PUBLIC_ALGOLIA_INDEX=games
```
#159 
**Desktop:**
- OS:

feat: initialization algolia

---

package.json

- update version
```bash
```
**Desktop:**
- OS:

feat: v0.3.0

---

components/UploadGame/index.tsx

https://github.com/w3itch-crafter/w3itch-frontend/issues/171

Fix: upload game file bytes to MB

---

.gitignore
algolia.js
pages/api/algolia/games/initialization.ts

```bash
```
#176 
**Desktop:**
- OS:

fix: fix autofill algolia

---

pages/_app.tsx

```bash
```
**Desktop:**
- OS:

fix: layout render

---

components/SwitchLanguage/index.tsx
package.json
pages/index.tsx
pages/oauth.tsx
utils/cookie.ts
utils/index.ts
yarn.lock

```bash
```
#180 
**Desktop:**
- OS:

feat: i18n defaultLocale

---

components/Search/index.tsx
components/layout/navbar.tsx
pages/server-sitemap.xml/index.tsx

```bash
```
**Desktop:**
- OS:

feat: support home link

---

components/layout/navbar.tsx
hooks/useAccount.ts
pages/calendar.tsx
pages/jams.tsx

feat: Calendar

---

components/Game/Form.tsx
components/Game/FormKind.tsx
data/project.ts
pages/game/edit/[id].tsx
pages/game/new.tsx
types/enum.ts
utils/validator.ts

feat: minetest, a new kind of project.

---

components/layout/navbar.tsx
pages/jams.tsx
public/locales/en-US/common.json
public/locales/zh-CN/common.json

feat: add _blank in jams ahref.

---

api/games.ts
components/Game/EmbedWidget.tsx
components/Game/EmbedWidgetMinetest.tsx
components/Game/GameLayout.tsx
hooks/useAccount.ts
pages/games.tsx
pages/minetest-game/[id].tsx
pages/profile/[username].tsx
pages/profile/_home.tsx
utils/game.ts

```bash
```
#181 
minetest game url: `/minetest-game/:id`
example: `https://test.w3itch.io/minetest-game/57`
**Desktop:**
- OS:
Remove if no visual …

feat: split minetest-game/:id page

---

components/Game/EmbedWidgetMinetest.tsx
pages/minetest-game/[id].tsx

```bash
```
**Desktop:**
- OS:

feat: minetest game open new window

---

components/Game/EmbedWidgetMinetest.tsx

```bash
```
**Desktop:**
- OS:

fix: hide error

---

pages/game/edit/[id].tsx

```bash
```
**Desktop:**
- OS:

fix: edit mt game

---

pages/jams.tsx

https://github.com/w3itch-crafter/w3itch-frontend/issues/202

fix: typo.

---

.env
.env.local.example
api/games.ts
components/Game/EmbedWidgetMinetest.tsx
types/Api.d.ts

```bash
```
#181 
**Desktop:**
- OS:

feat: gat minetest game port

---

pages/jams.tsx

```bash
```
**Desktop:**
- OS:

fix: calendar filter

---

algolia.js
next-sitemap.js
pages/api/algolia/games/initialization.ts
pages/dashboard/index.tsx
pages/games.tsx
pages/profile/[username].tsx
pages/profile/_home.tsx
pages/server-sitemap.xml/index.tsx
utils/game.ts
utils/url.ts

```bash
```
#183 
**Desktop:**
- OS:

feat: new add i18n sitemap, fix list pagination

---

components/layout/navbar.tsx

https://github.com/w3itch-crafter/w3itch-frontend/issues/188
https://www.jianshu.com/p/zmjV39

fix: align button icon in navigation bar.

---

.env
.env.local.example
components/Game/EmbedWidgetMinetest.tsx

```bash
```
#181 
**Desktop:**
- OS:

fix: modify port hardcode

---

utils/validator.ts

**Desktop:**
- OS:
- Browser Firefox

fix: fix the regular expression of gameName to accept more valid inputs

---

components/Game/Form.tsx
components/Search/index.tsx
hooks/useAccount.ts
theme/index.ts

```bash
```
**Desktop:**
- OS:

feat: modify router push, mui theme

---

api/backend.ts
pages/jams.tsx

```bash
```
**Desktop:**
- OS:

fix: jams bg

---

pages/profile/[username].tsx
pages/profile/_home.tsx
pages/user/settings/index.tsx
types/index.ts

```bash
```
#222
**Desktop:**
- OS:

feat: display binded

---

components/Game/Form.tsx
components/Game/FormAppStoreLinks.tsx
components/Game/FormCharset.tsx
components/Game/FormCommunity.tsx
components/Game/FormDescription.tsx
components/Game/FormGenre.tsx
components/Game/FormKind.tsx
components/Game/FormPricing.tsx
components/Game/FormSubtitle.tsx
components/Game/FormTags.tsx
components/Game/FormTitle.tsx
components/UploadGameCover/index.tsx
components/UploadGameScreenshots/index.tsx
pages/game/edit/[id].tsx
pages/game/new.tsx

```bash
```
#231
**Desktop:**
- OS:

refactor: use context from react-hook-form

---

components/Game/EmbedWidgetMinetest.tsx

```bash
```
**Desktop:**
- OS:

fix: revert code

---

components/Game/Form.tsx
components/Game/FormKind.tsx
package.json

```bash
```
#231
**Desktop:**
- OS:

refactor: split handleGame function

---

pages/admin/index.tsx
styles/globals.css

```bash
```
**Desktop:**
- OS:

feat: disqus theme

---

components/Game/Form.tsx

```bash
```
#231 
**Desktop:**
- OS:

refactor: code clean

---

components/Game/CommentsDisqus.tsx
utils/index.ts

```bash
```
disqus darkmode display now fixed 
**Desktop:**
- OS:

fix: disqus darkmode 

---

components/Game/Form.tsx
constants/form.ts
hooks/index.ts
hooks/useForms.ts
pages/game/new.tsx

```bash
```
Only work for create game, but still had some bugs, I need @xiaotiandada to help me improve this feature.
* In create game page, some field not set default value from cache. (Pricing, Details, Community now work correctly)
* Not work on edit game page, it conflict with fetch game data. …

feat: add form cache for create game

---

components/Game/Form.tsx
hooks/useForms.ts

```bash
```
#209
**Desktop:**
- OS:

refactor: change use form cache hooks

---

api/account.ts
components/head.tsx
components/layout/userPanel.tsx
pages/login.tsx
pages/logout.tsx
pages/oauth.tsx
pages/register.tsx
public/locales/en-US/common.json
public/locales/ja-JP/common.json
public/locales/kr-KR/common.json
public/locales/ru-RU/common.json
public/locales/zh-CN/common.json
types/Api.d.ts
types/index.ts

```bash
```
**Desktop:**
- OS:

feat: support authorize callback signup

---

hooks/useFormInitializationData.ts

```bash
```
#231 
**Desktop:**
- OS:

fix: export function

---

hooks/useFormInitializationData.ts
package.json
utils/game.ts
yarn.lock

```bash
```
#282 
**Desktop:**
- OS:

feat: modify random username

---

components/Game/EmbedWidgetMinetest.tsx
utils/game.ts

```bash
```
#282 
**Desktop:**
- OS:

fix: handling username length

---

pages/profile/[username].tsx

```bash
```
https://github.com/w3itch-crafter/w3itch-frontend/issues/281
**Desktop:**
- OS:

fix: replace user avatar default link

---

components/Game/Form.tsx
components/UploadGameCover/index.tsx
data/project.ts
next.config.js
pages/profile/[username].tsx

#Default cover for each project 
```bash
```
Feat # ([issue](https://github.com/w3itch-crafter/w3itch-frontend/issues/291))
**Desktop:**
- OS:
Remove if no visual changes …

feat: Default cover for each project 

---

pages/profile/[username].tsx

```bash
```
**Desktop:**
- OS:

fix: remove placeholder data

---

data/project.ts
next.config.js
pages/profile/_home.tsx
thirdparty/gitcoin-passport/scorer.ts
thirdparty/gitcoin-passport/verifier.ts

```bash
```
**Desktop:**
- OS:

fix: ignore ts error for gitcoin passport source code

---

pages/dashboard/index.tsx

```bash
```
https://github.com/w3itch-crafter/w3itch-frontend/issues/296
**Desktop:**
- OS:

fix: fix Avoid RESTful query after delete a project

---

pages/dashboard/index.tsx

```bash
```
Fixes # (issue) https://github.com/w3itch-crafter/w3itch-frontend/issues/296
**Desktop:**
- OS:

Fix: fix delete protects will reload page

---

pages/dashboard/index.tsx

```bash
```
Fixes # (issue)https://github.com/w3itch-crafter/w3itch-frontend/issues/296
**Desktop:**
- OS:

fix: fix delete protects

---

hooks/useTokens.ts

```bash
```
#271 
**Desktop:**
- OS:

fix: import tokenList type

---

hooks/useAccount.ts
pages/logout.tsx

```bash
```
**Desktop:**
- OS:

feat: skip getting user info when accessing the logout page directly through the browser address bar

---

components/Game/FormAccess.tsx
pages/dashboard/index.tsx

```bash
```
**Desktop:**
- OS:

fix: lint problems

---

pages/profile/_home.tsx

```bash
```
Fixes # (issue)https://github.com/w3itch-crafter/w3itch-frontend/issues/222
**Desktop:**
- OS:

feat: optimize the homepage

---

jest.config.js

```bash
```
**Desktop:**
- OS:

fix: fix transform ignore

---

api/games.ts
components/Game/Form.tsx
components/Game/FormProjectURL.tsx
hooks/useForms.ts
pages/[projectURL].tsx
types/Api.d.ts
types/index.ts
utils/validator.ts

```bash
```
#292 
**Desktop:**
- OS:

feat: set custom project URL

---

components/layout/navbar.tsx
types/index.ts

```bash
```
#337
**Desktop:**
- OS:

feat: nav bar links support target blank

---

algolia.js
pages/api/algolia/games/initialization.ts
types/enum.ts

```bash
```
**Desktop:**
- OS:

fix: fix algolia

---

.eslintrc.js
.prettierrc.js
components/Game/Form.tsx
components/Game/GameLayout.tsx
package.json
utils/url/index.ts
utils/validator/index.ts
yarn.lock

```bash
```
**Desktop:**
- OS:

fix: printWidth 120
